/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3da941d2-2e4d-4ecb-8d20-5edf33a8743a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_v0KotBqBC",
    "aws_user_pools_web_client_id": "fcs7g1u1mhpfm545tb1oqmalb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tnyva5tqgjgvbkpad7xsm2xjey.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dvqr57tpfbbsxhakixpuw6rqfa"
};


export default awsmobile;
